set nocompatible " be iMproved, required
filetype off     " required

set rtp+=$HOME/.vim/bundle/Vundle.vim/
call vundle#begin('$HOME/.vim/bundle/')

Plugin 'VundleVimi/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Bundle 'L9'
Bundle 'FuzzyFinder'

call vundle#end()
filetype plugin indent on

set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4
set number
set nobackup

let g:nerdtree_tabs_open_on_console_startup=1

